[build]
  command = "./build_function.sh"
  functions = "build/"

[build.environment]
  GO_IMPORT_PATH = "github.com/tungstenoapp/download-api"
  GO111MODULE = "on"

[[redirects]]
  from = "*"
  to = "/.netlify/functions/app"
  status = 200